version: '3.8'

services:
  back-end:
    build:
      context: .
      dockerfile: back-end/AutoSelect.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8083:8080"
